# Generated by Django 2.2.4 on 2019-08-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='index',
            field=models.SmallIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='income',
            name='index',
            field=models.SmallIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.CategoryExpense'),
        ),
    ]
