# Generated by Django 2.2.4 on 2019-08-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190824_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='income',
        ),
    ]
