# Generated by Django 2.2.4 on 2019-08-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190825_2357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='budget',
            managers=[
            ],
        ),
    ]
