# Generated by Django 2.2.4 on 2019-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190826_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='creation_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='budget',
            name='purpose_save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='purpose_spend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
