# Generated by Django 2.2.4 on 2019-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20190826_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='purpose_save',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='purpose_spend',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_purpose_save_money',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='purpose',
            field=models.IntegerField(default=0),
        ),
    ]
