# Generated by Django 2.2.4 on 2019-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20190826_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
