# Generated by Django 2.2.4 on 2019-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_budgetline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='short_description',
            field=models.CharField(default='test item', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='is_purpose_save_money',
            field=models.BooleanField(default=True, verbose_name='Purpose save money'),
        ),
    ]
