# Generated by Django 2.2.4 on 2019-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20190827_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
