# Generated by Django 2.2.4 on 2019-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20190830_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default='2019-09-09'),
            preserve_default=False,
        ),
    ]
